version: "3"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wordi
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
